- name: install redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/redis.conf 
  ansible.builtin.replace:
    path:  /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes

    
