- name: copying the mongodb repo
  ansible.builtin.import_role:
   name: common
   tasks_from: mongodb

- name: installling mongodb 
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: starting and enabling the mongodb 
  ansible.builtin.service:
    name: mongodb-org
    state: started
    enabled: yes



