- name: copying the mongodb repo
  ansible.builtin.import_role:
   name: common
   tasks_from: mongodb

- name: installling mongodb 
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: starting and enabling the mongodb 
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: resatrting the mongod service
  ansible.builtin.service:
    name: mongod
    state: restarted
    


