- name: disabling mysql
  ansible:builtin.service:
    name: mysql
    state: disabled

- name: copying mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d

- name: installing mysql server
  ansible.builtin.yum:
    name: mysqld
    state: installed

- name: starting mysqld service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: change the default username
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

- name: change the permissions of roboshop user
  ansible.builtin.shell: mysql -uroot -pRoboShop@1


