- name: setup and install nodejs
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs

- name: creating roboshop user
  ansible.builtin.import_role:
    name: common
    tasks_from: user

- name: creating /app directory
  ansible.builtin.import_role:
    name: common
    tasks_from: app-directory

- name: downlaod the application code in /app directory
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    dest: /tmp

    