- name: setup and install nodejs
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs

- name: creating roboshop user
  ansible.builtin.import_role:
    name: common
    tasks_from: user

- name: creating /app directory
  ansible.builtin.import_role:
    name: common
    tasks_from: app-directory

