- name: check if /app directory present  or not
  ansible.builtin.stat:
    path: /app
  register: directory

- name: print the output of directory
  ansible.builtin.debug:
    msg: "{{directory}}"

- name: print the exists status of directory
  ansible.builtin.debug:
    msg: "{{directory.stat.exists}}"

- name: creating /app directory
  ansible.builtin.file:
    path: /app
    state: directory
  when: directory.stat.exists == false



